CREATE TABLE Empresa_Telefonia_Fija(
    NIT VARCHAR(15) NOT NULL,
    Razon_Social VARCHAR(200) NOT NULL,
    Costo_segundo FLOAT NOT NULL,
    Fecha_Creacion DATE NOT NULL,
    Esta_Activo CHAR(1) NOT NULL,
    Periodicidad_Archivo NUMERIC NOT NULL,
    Primer_Parametro_Archivo NUMERIC NOT NULL,
    Segundo_Parametro_Archivo NUMERIC NOT NULL,
    Tercer_Parametro_Archivo NUMERIC NOT NULL,
    Cuarto_Parametro_Archivo NUMERIC NOT NULL,
    Quinto_Parametro_Archivo NUMERIC NOT NULL,
    PRIMARY KEY(NIT)
);

CREATE TABLE Cliente_Empresa(
    Id_Registro NUMERIC GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Esta_Activo CHAR(1) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    Nit VARCHAR(15) NOT NULL,
    PRIMARY KEY(Id_Registro)
);

CREATE TABLE Cliente(
    Telefono VARCHAR(15) NOT NULL,
    Cedula VARCHAR(10) NOT NULL,
    Primer_Nombre VARCHAR(100) NOT NULL,
    Segundo_Nombre VARCHAR(100) NOT NULL,
    Primer_Apellido VARCHAR(100) NOT NULL,
    Segundo_Apellido VARCHAR(100) NOT NULL,
    PRIMARY KEY(Telefono)
);

CREATE TABLE Llamada(
    Id_Llamada NUMERIC GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Duracion NUMERIC NOT NULL,
    Telefono_Destino VARCHAR(15) NOT NULL,
    Fue_Reportada CHAR(1) NOT NULL,
    Fecha DATE NOT NULL, 
    Telefono VARCHAR(15) NOT NULL,
    PRIMARY KEY(Id_Llamada)
);

ALTER TABLE Cliente_Empresa
    ADD CONSTRAINT FK_Telefono
    FOREIGN KEY(Telefono)
    REFERENCES Cliente(Telefono);
    
ALTER TABLE Cliente_Empresa
    ADD CONSTRAINT FK_Nit
    FOREIGN KEY(Nit)
    REFERENCES Empresa_Telefonia_Fija(Nit);
    
ALTER TABLE Llamada
    ADD CONSTRAINT FK_TelefonoLlamada
    FOREIGN KEY(Telefono)
    REFERENCES Cliente(Telefono);
    
CREATE INDEX Cedula_Index ON Cliente(Cedula);

    