create or replace NONEDITIONABLE PROCEDURE PRO_REPORTAR_LLAMADAS_EMPRESA(Nitp VARCHAR2) AS
    CURSOR LLAMADAS_A_ACTUALIZAR IS SELECT * FROM LLAMADA WHERE TELEFONO IN (SELECT CLIENTE_EMPRESA.TELEFONO FROM CLIENTE_EMPRESA WHERE NIT = NITp) AND fue_reportada = '0' FOR UPDATE OF fue_reportada;
    LLAMADA_REG llamada%ROWTYPE;
BEGIN
    OPEN LLAMADAS_A_ACTUALIZAR;
        LOOP
            FETCH LLAMADAS_A_ACTUALIZAR INTO LLAMADA_REG;
            UPDATE llamada SET llamada.fue_reportada = '1' WHERE llamada.id_llamada = LLAMADA_REG.id_llamada;
        END LOOP;        
    CLOSE LLAMADAS_A_ACTUALIZAR;
END;