create or replace NONEDITIONABLE PROCEDURE PRO_REPORTAR_LLAMADAS_EMPRESA(Nitp VARCHAR2) AS
    CURSOR LLAMADAS_A_ACTUALIZAR IS SELECT LLAMADA.fue_reportada FROM LLAMADA WHERE TELEFONO IN (SELECT CLIENTE_EMPRESA.TELEFONO FROM CLIENTE_EMPRESA WHERE NIT = NITp) AND fue_reportada = '0' FOR UPDATE;
    ESTADO_ANTERIOR llamada.fue_reportada%TYPE;
BEGIN
    OPEN LLAMADAS_A_ACTUALIZAR;
        LOOP
            FETCH LLAMADAS_A_ACTUALIZAR INTO ESTADO_ANTERIOR;
            EXIT WHEN LLAMADAS_A_ACTUALIZAR%notfound;
            UPDATE llamada SET llamada.fue_reportada = '1' WHERE CURRENT OF LLAMADAS_A_ACTUALIZAR;
        END LOOP;        
    CLOSE LLAMADAS_A_ACTUALIZAR;
END;